### ISSUE TITLE
Issue while running script

### ISSUE THREAD

**Issue by alisentinel** [AgiMaulana/Instagram-Comments-Scraper#2]
Hello, I tried to use this script to export my post comments but it returned me this error:

`DevTools listening on ws://127.0.0.1:50372/devtools/browser/27e55efd-868a-47ee-be40-8ea50e4f0fdc
[8516:1592:0609/184722.876:ERROR:browser_process_sub_thread.cc(221)] Waited 420 ms for network service`
And suddenly closed the chrome web drive

How to resolve it?
Thanks

**Comment by AgiMaulana** [comment]
did you run the script on Windows? If yes, you can check this first perhaps this explanation can help you https://stackoverflow.com/a/56485360/2741453

**Comment by alisentinel** [comment]
Yes, I'm using windows 10, I tried to resolve it but I couldn't
I added some arguments to webdriver but nothing changed
Here is my new code:
```from selenium import webdriver
from selenium.webdriver.chrome.options import Options
chrome_options = Options()
chrome_options.add_argument("--enable-features=NetworkService")
chrome_options.add_argument("--enable-features=NetworkServiceWindowsSandbox")
driver = webdriver.Chrome(options=chrome_options)

**Comment by alisentinel** [comment]
It seems that scripts isn't working more at all, it closed the browser, I've turned on the verbose level

VERBOSE log: https://pastebin.com/fBciFt2X

It just exported first 13 comments, not more.

**Comment by alisentinel** [comment]
> Yes, I'm using windows 10, I tried to resolve it but I couldn't
> I added some arguments to webdriver but nothing changed
> Here is my new code:
> 
> ```
> from selenium.webdriver.chrome.options import Options
> chrome_options = Options()
> chrome_options.add_argument("--enable-features=NetworkService")
> chrome_options.add_argument("--enable-features=NetworkServiceWindowsSandbox")
> driver = webdriver.Chrome(options=chrome_options)
> ```

For more details I've turned on the VERBOSE level, pasted the output here: https://pastebin.com/fBciFt2X

**Comment by AgiMaulana** [comment]
according to [this](https://stackoverflow.com/questions/55069656/please-protect-ports-used-by-chromedriver-and-related-test-frameworks-to-prevent) and [this](https://stackoverflow.com/questions/55442679/how-do-i-protect-the-ports-that-chromedriver-use) Stackoverflow's question, please update your chrome and chromedriver version

**Comment by AgiMaulana** [comment]
there is no an update from the author. I decided to close this issue.
